[project]
name = "katbot"
version = "1.2.0"
readme="README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
    "bitsandbytes",
    "datasets",
    "hf_xet",
    "numpy",
    "peft",
    "python-dotenv",
    "requests",
    "requests-oauthlib",
    "tenacity",
    "torch",
    "tqdm",
    "transformers",
    "trl",
    "tzdata",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [
   { index = "pytorch-cu128" }
]
torchvision = [
  { index = "pytorch-cu128" }
]

[dependency-groups]
dev = [
    "ruff",
]

[tool.ruff]
line-length = 100
target-version = "py312"
fix=true
lint.select = [
    "B",  # bugbear
    "E",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
    "RUF",  # ruff
    "UP",  # pyupgrade
]
