[project]
name = "katbot"
version = "1.0.1"
readme="README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
    "python-dotenv",
    "requests",
    "requests-oauthlib",
    "tenacity",
    "tzdata",
]

[dependency-groups]
dev = [
    "ruff",
]

[tool.ruff]
line-length = 100
target-version = "py312"
fix=true
lint.select = [
    "B",  # bugbear
    "E",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
    "RUF",  # ruff
    "UP",  # pyupgrade
]
